background.image = Image("background.png");
background.sprite = Sprite(background.image);
background.sprite.SetX(0);
background.sprite.SetY(0);
background.sprite.SetZ(10000);

logo.image = Image("arch-logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth()  / 2 - logo.image.GetWidth()  / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
logo.sprite.SetZ(11000);

